In [1]:
import pandas as pd
import pycaret
from pycaret.regression import *

In [2]:
# Read the training data
training_df = pd.read_csv('../data/final_datasets/transformed_datasets/transformed_reduced_smote_training_data.csv')

# Read the test data
test_df = pd.read_csv('../data/final_datasets/transformed_datasets/transformed_reduced_test_data.csv')

# Read the submission data
submission_df = pd.read_csv('../data/initial_datasets/Submission_template_UHI2025-v2.csv')

In [3]:
submission_df.columns

Index(['Longitude', 'Latitude', 'UHI Index'], dtype='object')

In [4]:
# Hay que bajar la cantidad de variables y tunear a fondo.

In [5]:
test_df

,0,1,2,3,4,5,6,7,8,9,...,62,63,64,65,66,67,68,69,70,71
0,2.024929,0.038756,-1.359980,1.882409,1.233216,-0.160048,0.274618,0.601326,-1.367055,-1.418223,...,-0.228147,-0.147852,-0.217653,-0.158099,0.012480,-0.172429,-0.017267,1.866595,0.714657,-0.278250
1,2.497972,0.041555,-1.311989,1.482754,2.039140,-0.167127,0.433058,0.584100,-1.270224,-1.231639,...,-0.213492,-0.108307,-0.217653,-0.131748,0.054162,-0.028796,0.024477,1.868389,0.714657,-0.770584
2,-0.276224,0.066418,-0.714078,0.166692,-0.385489,0.007183,0.430823,-0.270308,-0.618357,-0.614930,...,-1.495961,-1.611828,-0.646439,-1.089017,-1.316951,-0.890594,0.305430,0.321389,0.814883,-1.396578
3,-0.112987,-0.029917,0.712894,-0.825743,-1.499013,0.814100,-1.771427,-0.108291,-0.362801,-0.592344,...,-0.231393,-0.136333,-0.055224,-0.096949,0.095662,0.043021,0.158350,2.230033,1.298092,-0.191556
4,0.722014,0.051180,-0.363650,0.900821,1.273853,-0.144012,0.760619,0.739212,0.109378,0.114711,...,-0.627075,-0.810267,-0.989880,-0.591049,-0.614711,-0.675144,0.170902,1.332199,1.007370,-0.818069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1035,-0.974078,-0.061811,0.926556,-0.991425,-1.333696,-0.060677,-1.256677,-0.351220,0.205212,0.346468,...,0.688906,0.695221,1.235262,0.976872,0.982160,0.617553,-0.641563,-0.608126,-0.105403,-0.423311
1036,1.890959,0.032209,-1.171516,1.471116,1.154245,-0.121725,-0.251234,0.266692,-1.271222,-0.989080,...,-1.174891,-0.759467,-0.451662,-0.055117,-0.758741,1.838433,-0.475696,-0.584813,-0.425329,0.577911
1037,0.615589,0.046728,-0.272430,0.064741,1.033525,-0.086794,0.529313,0.142017,-0.018400,0.155956,...,1.153791,0.994615,0.664695,0.014143,-0.351044,1.048452,-0.071290,0.384751,-0.099761,0.359691
1038,-0.566842,0.046715,0.519096,-0.546294,-0.387250,0.032557,-1.008783,-0.192629,1.790456,1.780218,...,1.163265,1.258485,1.098298,1.370311,1.263081,0.043021,-0.412412,-0.441351,-0.687841,0.385269
1039,-1.065819,-0.118709,0.476980,-0.722033,-0.496829,-0.051316,0.538636,-0.388161,-0.012410,0.028294,...,1.234476,1.277615,1.225626,1.327558,1.380429,-0.603328,-0.786384,-1.006233,-1.166735,-0.385300

In [6]:
submission_df

      Longitude   Latitude  UHI Index
0    -73.971665  40.788763        NaN
1    -73.971928  40.788875        NaN
2    -73.967080  40.789080        NaN
3    -73.972550  40.789082        NaN
4    -73.969697  40.787953        NaN
...         ...        ...        ...
1035 -73.919388  40.813803        NaN
1036 -73.931033  40.833178        NaN
1037 -73.934647  40.854542        NaN
1038 -73.917223  40.815413        NaN
1039 -73.911645  40.804402        NaN

[1040 rows x 3 columns]

In [7]:
training_df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
       '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48',
       '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60',
       '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71',
       'UHI Index binned'],
      dtype='object')

In [8]:
# Describe the training data
training_df.describe()

,0,1,2,3,4,5,6,7,8,9,...,63,64,65,66,67,68,69,70,71,UHI Index binned
count,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000,...,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000
mean,0.015562,0.014065,-0.015001,0.028876,0.032171,0.004629,0.024350,0.006126,0.020339,0.017763,...,-0.133408,-0.111577,-0.121071,-0.150189,-0.125740,-0.000537,0.006222,-0.039398,-0.080832,1.001047
std,1.007949,0.743861,1.009628,1.011329,0.976568,0.783067,0.952851,0.841933,0.963035,0.963671,...,1.065021,1.060660,1.098793,1.076983,0.901244,0.942133,0.963267,0.969954,0.923118,0.025932
min,-2.352210,-34.507520,-3.656758,-2.569003,-4.157917,-49.212981,-6.926961,-45.382907,-1.880496,-2.007267,...,-3.466607,-3.406382,-3.716766,-3.631161,-1.521620,-1.628591,-1.371903,-1.473154,-1.898800,0.956000
25%,-0.723820,-0.005169,-0.380839,-0.683756,-0.623374,-0.121435,-0.460278,-0.161630,-0.537770,-0.556966,...,-0.797052,-0.680431,-0.658564,-0.811236,-0.741567,-0.521017,-0.631822,-0.798044,-0.647952,0.978500
50%,-0.337306,0.034119,0.235289,-0.228197,-0.093124,-0.011917,0.146311,-0.049151,-0.091535,-0.118517,...,-0.034146,-0.011164,0.049771,0.042700,-0.245170,-0.180148,-0.169630,-0.049056,-0.048949,1.001000
75%,0.490184,0.050456,0.666549,0.419751,0.540308,0.088714,0.642843,0.159349,0.408972,0.421458,...,0.723175,0.618306,0.626775,0.617599,0.322141,0.327162,0.494153,0.626016,0.452497,1.023500
max,3.304033,30.040131,2.173644,3.655408,3.430550,30.658948,4.254628,20.554501,8.149746,8.063442,...,2.165207,4.447804,3.126792,1.972261,4.576972,7.489311,3.914560,3.683458,3.177989,1.045500

In [9]:
test_df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
       '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48',
       '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60',
       '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71'],
      dtype='object')

In [10]:
# Describe the test data
test_df.describe()

,0,1,2,3,4,5,6,7,8,9,...,62,63,64,65,66,67,68,69,70,71
count,1.040000e+03,1.040000e+03,1.040000e+03,1040.000000,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,...,1040.000000,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1040.000000,1.040000e+03,1.040000e+03
mean,2.732857e-17,-3.074464e-17,6.148928e-16,0.000000,-1.366428e-17,1.195625e-17,-1.468910e-16,-5.465713e-17,-8.198570e-17,1.366428e-17,...,0.000000,-3.006142e-16,-2.814842e-15,-1.284443e-15,1.913000e-16,8.198570e-17,-2.732857e-17,0.000000,-1.229786e-16,-2.418578e-15
std,1.000481e+00,1.000481e+00,1.000481e+00,1.000481,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,...,1.000481,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481,1.000481e+00,1.000481e+00
min,-1.353901e+00,-3.153941e+01,-3.388084e+00,-1.755168,-3.475165e+00,-1.985384e+01,-4.816771e+00,-9.110973e+00,-1.857203e+00,-1.843438e+00,...,-3.789881,-3.400037e+00,-3.193687e+00,-3.817908e+00,-3.640791e+00,-1.536942e+00,-1.632112e+00,-1.397167,-1.509229e+00,-1.733795e+00
25%,-7.383444e-01,1.659990e-02,-3.717728e-01,-0.702025,-6.803426e-01,-8.783032e-02,-5.709972e-01,-2.993356e-01,-5.934002e-01,-6.036368e-01,...,-0.612650,-5.339963e-01,-4.933013e-01,-3.567244e-01,-5.280692e-01,-6.751442e-01,-5.460280e-01,-0.652211,-6.888369e-01,-6.922991e-01
50%,-3.094001e-01,3.876814e-02,2.477247e-01,-0.267544,-1.482774e-01,-3.874400e-02,1.442218e-01,-1.210552e-01,-1.142332e-01,-1.258837e-01,...,0.222050,9.449097e-02,7.898636e-02,1.387517e-01,2.092331e-01,-2.442452e-01,-2.443066e-01,-0.161002,6.106797e-03,-5.031516e-02
75%,4.549036e-01,4.964772e-02,6.764326e-01,0.357144,5.606861e-01,1.167312e-02,6.915538e-01,2.118951e-01,3.669304e-01,3.798569e-01,...,0.735716,7.200019e-01,6.333792e-01,5.960028e-01,6.572803e-01,4.021033e-01,4.416367e-01,0.512821,6.456276e-01,4.108458e-01
max,3.207504e+00,3.865299e+00,2.091750e+00,3.317940,3.304932e+00,1.435098e+01,3.769261e+00,1.792345e+01,7.027352e+00,6.380003e+00,...,1.956013,2.129460e+00,4.552672e+00,3.172588e+00,1.970321e+00,4.064745e+00,7.175662e+00,3.664056,3.371971e+00,2.512378e+00

In [ ]:
s = setup(training_df, target = 'UHI Index binned' 
          , session_id = 123#, feature_selection = True, n_features_to_select=30
         )

In [ ]:
best = compare_models()

In [ ]:
best = create_model('knn')

In [ ]:
tuned_rf = tune_model(best, n_iter=300, optimize = 'R2')

In [ ]:
plot_model(best, plot = 'residuals')

In [ ]:
plot_model(best, plot = 'feature')

In [ ]:
holdout_pred = predict_model(tuned_rf)

In [ ]:
predictions = predict_model(tuned_rf, data = test_df)
predictions.head()

In [ ]:
save_model(tuned_rf, '../models/knn_tunned_model_v5')

In [ ]:
predictions

In [17]:
submission_df['UHI Index'] = predictions['prediction_label']

In [18]:
submission_df.to_csv('../data/submissions/submission-v22.csv', index = False)

# Blend Approach

In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV, train_test_split, RandomizedSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, VotingRegressor
from sklearn.svm import SVR
from sklearn.metrics import r2_score

# Load your data. Replace the paths with your actual data sources.
# For example:
# training_df = pd.read_csv('path_to_training_data.csv')

# Assume your training_df contains features and target 'UHI Index binned'.
X = training_df.drop('UHI Index binned', axis=1)
y = training_df['UHI Index binned']

# Split into training and validation sets.
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

### --- KNN Pipeline and Grid Search ---
pipeline_knn = Pipeline([
    ('scaler', StandardScaler()),  # KNN requires scaling
    ('knn', KNeighborsRegressor())
])
param_grid_knn = {
    'knn__n_neighbors': [3, 5, 7, 9, 11],
    'knn__weights': ['uniform', 'distance'],
    'knn__p': [1, 2]  # p=1: Manhattan, p=2: Euclidean
}
grid_knn = GridSearchCV(pipeline_knn, param_grid_knn, cv=5, scoring='r2', n_jobs=-1)
grid_knn.fit(X_train, y_train)
knn_best = grid_knn.best_estimator_
print("Best KNN Parameters:", grid_knn.best_params_)
print("KNN Validation R^2:", r2_score(y_val, knn_best.predict(X_val)))

### --- Random Forest Pipeline and Grid Search ---
pipeline_rf = Pipeline([
    ('rf', RandomForestRegressor(random_state=42))
])
param_grid_rf = {
    'rf__n_estimators': [50, 100, 200],
    'rf__max_depth': [None, 10, 20, 30],
    'rf__min_samples_split': [2, 5, 10]
}
grid_rf = GridSearchCV(pipeline_rf, param_grid_rf, cv=5, scoring='r2', n_jobs=-1)
grid_rf.fit(X_train, y_train)
rf_best = grid_rf.best_estimator_
print("Best RF Parameters:", grid_rf.best_params_)
print("Random Forest Validation R^2:", r2_score(y_val, rf_best.predict(X_val)))

Best KNN Parameters: {'knn__n_neighbors': 3, 'knn__p': 1, 'knn__weights': 'distance'}
KNN Validation R^2: 0.9932218739945098
Best RF Parameters: {'rf__max_depth': 30, 'rf__min_samples_split': 2, 'rf__n_estimators': 200}
Random Forest Validation R^2: 0.9864525157729036

In [12]:
## For the following models i will use random search instead of grid search
### --- SVR Pipeline and Grid Search ---
pipeline_svr = Pipeline([
    ('scaler', StandardScaler()),  # SVR benefits from scaling
    ('svr', SVR())
])
param_grid_svr = {
    'svr__kernel': ['rbf', 'linear'],
    'svr__C': [0.1, 1, 10],
    'svr__epsilon': [0.01, 0.1, 1]
}
grid_svr = RandomizedSearchCV(pipeline_svr, param_grid_svr, cv=5, scoring='r2', n_iter=10, n_jobs=-1)
grid_svr.fit(X_train, y_train)
svr_best = grid_svr.best_estimator_
print("Best SVR Parameters:", grid_svr.best_params_)
print("SVR Validation R^2:", r2_score(y_val, svr_best.predict(X_val)))

### --- Gradient Boosting Pipeline and Grid Search ---
pipeline_gbr = Pipeline([
    ('gbr', GradientBoostingRegressor(random_state=42))
])
param_grid_gbr = {
    'gbr__n_estimators': [50, 100, 200],
    'gbr__max_depth': [3, 5, 7],
    'gbr__learning_rate': [0.01, 0.1, 0.2]
}
grid_gbr = RandomizedSearchCV(pipeline_gbr, param_grid_gbr, cv=5, scoring='r2', n_iter=10, n_jobs=-1)
grid_gbr.fit(X_train, y_train)
gbr_best = grid_gbr.best_estimator_
print("Best GBR Parameters:", grid_gbr.best_params_)
print("Gradient Boosting Validation R^2:", r2_score(y_val, gbr_best.predict(X_val)))

### --- Blended Ensemble with VotingRegressor ---
# Combine the best models from KNN, Random Forest, SVR, and Gradient Boosting.
ensemble_model = VotingRegressor(estimators=[
    ('knn', knn_best),
    ('rf', rf_best),
    ('svr', svr_best),
    ('gbr', gbr_best)
])
ensemble_model.fit(X_train, y_train)
ensemble_pred = ensemble_model.predict(X_val)
print("Blended Ensemble Validation R^2:", r2_score(y_val, ensemble_pred))

Best SVR Parameters: {'svr__kernel': 'rbf', 'svr__epsilon': 0.01, 'svr__C': 10}
SVR Validation R^2: 0.9381777587975895
Best GBR Parameters: {'gbr__n_estimators': 200, 'gbr__max_depth': 5, 'gbr__learning_rate': 0.2}
Gradient Boosting Validation R^2: 0.9756435950230785
Blended Ensemble Validation R^2: 0.9865293446694606

In [13]:
# Now you can use the ensemble model to make predictions on out submission data.
predictions = ensemble_model.predict(test_df)

In [14]:
predictions

array([0.97107879, 0.9723956 , 0.9737089 , ..., 1.0402502 , 1.036371  ,
       1.03400457])

In [15]:
# Save the predictions to a CSV file.
submission_df['UHI Index'] = predictions
submission_df.to_csv('../data/submissions/submission-v23.csv', index = False)